//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSString;

@interface NetworkControl : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int maxNoopInterval; // @dynamic maxNoopInterval;
@property(nonatomic) unsigned int minNoopInterval; // @dynamic minNoopInterval;
@property(nonatomic) int noopIntervalTime; // @dynamic noopIntervalTime;
@property(retain, nonatomic) NSString *portList; // @dynamic portList;
@property(retain, nonatomic) NSString *timeoutList; // @dynamic timeoutList;
@property(nonatomic) int typingInterval; // @dynamic typingInterval;

@end

[ProtoMember(1, Options = MemberSerializationOptions.Required)]
            public string portList;
            [ProtoMember(2, Options = MemberSerializationOptions.Required)]
            public string timeoutList;
            [ProtoMember(3, Options = MemberSerializationOptions.Required)]
            public uint minNoopInterval;
            [ProtoMember(4, Options = MemberSerializationOptions.Required)]
            public uint maxNoopInterval;
            [ProtoMember(5, Options = MemberSerializationOptions.Required)]
            public int typingInterval;
            [ProtoMember(7, Options = MemberSerializationOptions.Required)]
            public int noopIntervalTime;