//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ProtobufCGIWrap, ProtobufEventHandler, ProtobufPrtlChannel;

@interface ProtobufEvent : NSObject

@property(nonatomic) _Bool m_bSpeedy; // @synthesize m_bSpeedy;
@property(readonly) ProtobufCGIWrap *m_pbCGIWrap; // @synthesize m_pbCGIWrap;

@end

