//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



@class NSData, WXCPbQcwxtalkHead;

@interface WXCPbQcwxtalkPackage : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSData *body; // @dynamic body;
@property(retain, nonatomic) WXCPbQcwxtalkHead *head; // @dynamic head;

@end

